language: scala
dist: trusty
sudo: false

jdk:
  - oraclejdk8

scala:
  - 2.11.12

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt -jvm-opts travis/jvmopts.test test


before_cache:
  - rm -rf $HOME/.ivy2/local
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
  - find $HOME/.sbt -name "*.lock" -delete


notifications:
 email:
   recipients:
     - fabio@teamdigitale.governo.it
     - fabiana@teamdigitale.governo.it
