language: scala
dist: trusty
sudo: true
group: beta

jdk:
  - oraclejdk8

scala:
  - 2.11.12

script:
   - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts travis/jvmopts test

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  - rm -rf $HOME/.ivy2/local
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt -jvm-opts travis/jvmopts.test test


#notifications:
#  email:
#    recipients:
#      - fabio@teamdigitale.governo.it
#      - fabiana@teamdigitale.governo.it
