---
  swagger: "3.0"
  info:
    title: "Storage Manager Api"
    description: "Storage Manager Api"
    version: "1.0.0-SNAPSHOT"
  consumes:
    - application/json
  produces:
    - application/json
